### PR TITLE
Remove superfluous code

### LINKED ISSUE #95: If statement within parseHost will never be false
The following line looks to me like a typo:
```php
        if ($this->isMultiLabelDomain($host) || !$this->isIpv4Address($host)) {
            $subdomain = $this->getSubdomain($host);
            $registrableDomain = $this->getRegistrableDomain($host);
            $publicSuffix = $this->getPublicSuffix($host);
        }
```
https://github.com/jeremykendall/php-domain-parser/blob/151e09cf/src/Pdp/Parser.php#L131

`10.10.10.10` has a dot => true
`localhost` has no dot but is not an IP address => true
`example.com` has a dot => true

I fail to see what this is meant to filter out.

Should this not be an `&&` instead?

### PR DESCRIPTION
**Pull request by mikegreiling**
closes #95

### CODE REVIEW

**Comment by jeremykendall** [comment]
Hey @mikegreiling,

Thank you for so many amazing PRs! So you know, I'm _crazy_ busy with @GraphStory right now, so while I promise to dig in, I can't promise that it'll be right away.

Just wanted to let you know I'm not going to be ignoring you. Thanks again!

**Comment by jeremykendall** [comment]
@mikegreiling Ignore that test failure. I caused it in what must have been some really bizarre Travis edge case.

**Comment by jeremykendall** [comment]
Great catches! Thanks again.

**Comment by mikegreiling** [comment]
no problem

**Pull request merged**
