### PR TITLE
Adding PHP8 support to v5 using @szepeviktor fix

### PR DESCRIPTION
**Pull request by nyamsprod**
Adding support to PHP8 to v5 to ease migration for legacy application
based on closed PR #288

### CODE REVIEW

**Comment by szepeviktor** [comment]
https://travis-ci.org/github/jeremykendall/php-domain-parser/jobs/737809661 🏃‍♂️

**Comment by szepeviktor** [comment]
Very nice!

> Pdp\Tests\CurlHttpClientTest::testConstructorThrowsException

Only 1 failure.

**Comment by szepeviktor** [comment]
@nyamsprod Why bother with HTTP bits and pieces, why not to use a mature Composer package?

**Comment by nyamsprod** [comment]
@szepeviktor this is only for the v5 version in v6 ... all this is completely rewritten and uses PSR contracts you can check the feature/v6 branches ...

**Pull request merged**
