### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by marknl**
'getRegistrableDomain' should be 'getRegisterableDomain'

### CODE REVIEW

**Comment by mikegreiling** [comment]
I don't think this is a type.  For one, "registrable" and not "registerable" is the actual name of the method within the library, not just in this instance but throughout.  Second, I believe "registrable" is the preferred spelling.

http://www.merriam-webster.com/dictionary/registrable

**Comment by mikegreiling** [comment]
see also #85

**Comment by jeremykendall** [comment]
Thanks for the PR! As @mikegreiling said, the corrected spelling is, uh, correct for what will become the latest version of php-domain-parser.

**Comment by marknl** [comment]
Ahh ok, got it. It's already changed in the code for the next release, but not on packagist ;-)
A bit confusing, since packagist grabs an older version and people check github for the docs. The docs in the package are correct. This PR can indeed be closed.

**Comment by jeremykendall** [comment]
> A bit confusing, since packagist grabs an older version and people check github for the docs.

Totally understand. Sorry for the confusion.

**Pull request closed without merging**
