### PR TITLE
Create ManagerInterface; implement on Manager

### LINKED ISSUE #225: Create ManagerInterface to allow mocking of Manager with Mockery in unit tests
## Issue summary

I'm developing a service that uses a `Pdp\Manager` so as to get a `Pdp\Rules` instance from which I can then get the registrable domain for a given URL.

I'd like to mock a `Pdp\Manager` instance in unit tests. Unit tests are happy to assume that `Pdp\Manager` works correctly. The tests just care about the return values of `Pdp\Manager::getRules()` and `Pdp\Manager::refreshRules()`.

I should be able to create a mock `Pdp\Manager` instance with Mockery so as to mock the return values of this relevant public methods.

Mockery cannot create full mocks of classes declared as `final`, as is the case with `Pdp\Manager`. That the class is declared as final is fine in this case.

This would be a non-issue if `Pdp\Manager` implemented an interface against which mocks could be created.

Note: I have for now resorted to creating functional tests which mock the cache and http client passed to the `Pdp\Manager` constructor. This allows me to test my code without the tests having to make like HTTP requests when refreshing the PSL data. This works but is non-ideal as functional tests are more costly (take longer) than what the equivalent unit tests could be. 

### System informations

Not a bug ... but here's the info anyway.

| Information | Description |
|--------------|---------|
| Pdp version | 5.3.0 |
| PHP version | 7.2.7  |
| OS Platform | Ubuntu 14.04,16.04 |

## Standalone code, or other way to reproduce the problem

```php
<?php

// RulesFactory::__construct() takes a `Pdp\Manager` instance
// For the purposes of this example, it can be an empty class with only a constructor 
// that takes a `Pdp\Manager` instance as the only argument
use Foo\Services\Pdp\RulesFactory;

class FooTest extends \PHPUnit\Framework\TestCase
{
    public function testFoo()
    {
        $manager = \Mockery::mock(\Pdp\Manager::class);
        $rulesFactory = new RulesFactory($manager);     
    }
}
```

### Expected result

`$rulesFactory` should be a `Foo\Services\Pdp\RulesFactory` instance. Methods of this instance can be called in tests. Such methods make use of the mocked `Pdp\Manager` instance.

### Actual result

"Mockery\Exception: The class \Pdp\Manager is marked final and its methods cannot be replaced. Classes marked final can be passed in to \Mockery::mock() as instantiated objects to create a partial mock, but only if the mock is not subject to type hinting checks."

The latter part of the exception message ("only if the mock is not subject to type hinting checks") also prevents me from creating a partial mock from an instantiated `Pdp\Manager` instance as the example `RulesFactory` class is type-hinted to expect a `Pdp\Manager` argument.

### Interface solution

Create `Pdp\ManagerInterface` which defines the signatures for `getRules()` and `refreshRules()` and have `Pdp\Manager` implement this new interface.

I'm happy to pop together a PR to deal with this.

### PR DESCRIPTION
**Pull request by webignition**
## Introduction

Fixes #225 

### Describe the new/upated/fixed feature

Creates `ManagerInterface` which `Pdp\Manager` then implements. This allows mocks to be easily created against `ManagerInterface` for use in unit tests in external projects that make use of `Pdp\Manager` instances.

See PR #225 for detail.

### Backward Incompatible Changes

No backward incompatible changes.

### Targeted release version

The next release version, whatever that might be.

Since this is an incremental change adding no new functionality, a minor release 5.3.1 seems fine to me.

### PR Impact

No changes to the public API

## Open issues

None

### CODE REVIEW

**Comment by webignition** [comment]
The contribution docs state that changes must add tests to be accepted.

Just acknowledging here that this change does not add any tests. I believe no new tests are needed. That the current tests pass feels sufficient to me since no new functionality is being added.

**Comment by nyamsprod** [comment]
Why do you need the `refreshRules` in the interface ? IMHO only the `getRules` method is really needed. Forcing a builder to refresh means your are forcing a builder to do some caching too ?

**Comment by webignition** [comment]
Short version of why I specifically need this: this needs to be mocked in unit tests for code that makes use of a `Manager` object for the refreshing of locally-cached PSL data. Such unit tests shouldn't need to make filesystem calls or HTTP requests.

The current `Manager` implementation already has a `refreshRules()` method and does do some caching and so I don't see the addition of `ManagerInterface::refreshRules()` to present any problems.

That said, it could be argued that the functionality provided by `Manager::getRules()` and `Manager::refreshRules()` don't need to be part of the same interface. That the current `Manager` implementation provides both of these methods does not necessarily mean that both methods belong under the same interface.

When considering `ManagerInterface` as being an interface for the public methods currently provided by `Manager`, having both `getRules()` and `refreshRules()` as methods of the interface makes sense.

If you don't think that `refreshRules()` belongs in the same interface as `getRules()` (and I'm now wondering the same myself), perhaps `getRules()` and `refreshRules()` belong more correctly as methods of separate interfaces where `Manager` happens to implement both interfaces?

We could possibly factor out `ManagerInterface::getRules()` to `RuleProviderInterface::getRules()` and `ManagerInterface::refreshRules()` to `RuleMaintainerInterface::refreshRules()`.

I'm not sure if doing so is getting to abstract and is not over-engineering at present.

**Comment by nyamsprod** [comment]
> If you don't think that refreshRules() belongs in the same interface as getRules() (and I'm now wondering the same myself), perhaps getRules() and refreshRules() belong more correctly as methods of separate interfaces where Manager happens to implement both interfaces ?

TBH that's what I have always thought. Because the only thing the `getRules` method guarantee is that it does returns a `Rules` object from an URL. The added value of the "Manager" implementation is that it is "smart" enough not to make a HTTP Request for each demand, otherwise `Rules::createFromPath` would be enough.

**Comment by webignition** [comment]
I was previously skimming through the readme to find out how best to use the latest version of the package, having previously been on 1.x.

I can handle the retrieval and local-caching of PSL data directly without the need for using a `Manager` instance, making the need for this change somewhat less relevant.

**Comment by nyamsprod** [comment]
@webignition indeed ... that is also true. the `Manager` is an example on how to do it properly but I still think that depending on the requirements you may use other means to create/build a `Rules` object. I tried to make the code less dependent of the `Manager` in contrast to previous versions.

**Pull request closed without merging**
