### PR TITLE
Overall modification prompted by magic functions breaking phpspec tests.

### PR DESCRIPTION
**Pull request by Saeven**
Thanks for being open-minded about this one, really appreciate it.  

Mainly replaced magic FNs, and corrected some typos along the way.  Tests all fixed.  Recommend a major version increment since this'll be a BC if folks are using versions with typos or pseudo-public access.

* Fixed typo in 'isMultiLabelDomain' (was isMutliLabelDomain).
* Standardized use of Registrable vs. Registerable  (registrable is proper spelling)
* Removed magic getters, substituted with proper accessors
* Made private members previous accessed by accessors, protected to permit inheritance
* Changed all tests and docs to reflect changes

### CODE REVIEW

**Comment by Saeven** [comment]
Tests are passing on PHP7 on my local machine.  I'll set up PHP5 and give it a shot.

**Comment by jeremykendall** [comment]
Thanks for the PR! I'll review with an open mind :-)

> ... corrected some typos along the way.

Oops. Thanks!

**Comment by jeremykendall** [comment]
Tests are breaking b/c of an updated PSL, not your changes. I'm looking at that now.

**Comment by Saeven** [comment]
Ah you are a kind soul.  The hamsters were chewing at the wheel on that one.

**Comment by jeremykendall** [comment]
That happens from time-to-time, as the suffix list changes and new suffixes are added. I should set up something that watches the PSL feed and runs tests whenever the list updates, but that's a project for another day.

**Comment by Saeven** [comment]
Cool, let me know I can patch up the changes to get travis in the green

**Comment by jeremykendall** [comment]
Will do!

**Comment by Saeven** [comment]
Thanks for a great lib by the way, what a time saver.

**Comment by jeremykendall** [comment]
Something has come up and I likely won't be available for the rest of the day. Here's the PR that should fix the tests: https://github.com/jeremykendall/php-domain-parser/pull/62. Will you see if it fixes the test failures Travis found in this branch?

Thanks! I'll get back to this ASAP.

**Comment by Saeven** [comment]
All done!  Thanks again.

**Comment by jeremykendall** [comment]
@Saeven Hey! I'm back for a bit. A few things:

* I'd like to keep the private methods private in order to encourage the use of [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance).
* I'm in love with the getters, but I'd like to drop the setters. I feel like they're unnecessary in the context of this library and they're an addition (rather than simply replacing `__get()` with getters).
* I made some changes in the develop branch that seem to have caused conflicts in your PR. That's on me; I'll help fix them.
* Turns out there's a PR from last summer (bad maintainer!) that adds getters to the library. I'm going to merge that first (because he got here first) and then merge yours to add all of the other killer improvements you've made.

I hope that's not too discouraging. If you'd like help with any of those changes, please let me know.

**Comment by jeremykendall** [comment]
@Saeven Here's a comparison showing the changes necessary to resolve the conflicts that I caused: https://github.com/Saeven/php-domain-parser/compare/develop...jeremykendall:Saeven-develop.

Thanks!

**Comment by Saeven** [comment]
Merged down!

**Comment by jeremykendall** [comment]
Awesome!

I've been at it too long today. My eyes are crossing and I can barely read the screen. I'll merge tomorrow after some sleep. 

Thanks again!

**Comment by Saeven** [comment]
Very cool - look forward to seeing it trickle down composer! ;)

**Pull request merged**
