### PR TITLE
Implement file locking within PublicSuffixListManager class

### PR DESCRIPTION
**Pull request by mikegreiling**
Addresses issue #78 

To test concurrency, I inserted the following at [line 249](https://github.com/mikegreiling/php-domain-parser/blob/6454cf0ee215d8c1bf493c3da2e1cfeb8e2a6e43/src/Pdp/PublicSuffixListManager.php#L249):

``` php
echo "lock obtained for '$filepath'\n\n";
sleep(5);
```

Then ran the following commands within 5 seconds of eachother:

``` bash
$ time bin/update-psl 
Updating Public Suffix List.
lock obtained for /Users/mike/Projects/php-domain-parser/data/public-suffix-list.txt

lock obtained for /Users/mike/Projects/php-domain-parser/data/public-suffix-list.php

Update complete.

real    0m11.799s
user    0m0.388s
sys 0m0.028s
```

``` bash
$ time bin/parse
Array
(
    [scheme] => http
    [user] => user
    [pass] => pass
    [host] => www.pref.okinawa.jp
    [subdomain] => www
    [registrableDomain] => pref.okinawa.jp
    [publicSuffix] => okinawa.jp
    [port] => 8080
    [path] => /path/to/page.html
    [query] => query=string
    [fragment] => fragment
)
Host: http://user:pass@www.pref.okinawa.jp:8080/path/to/page.html?query=string#fragment
'okinawa.jp' IS a valid public suffix.

real    0m4.535s
user    0m0.071s
sys 0m0.013s
```

The blocking appears to be effective.

PHPUnit passes, but I did not achieve complete code coverage as I am not sure how to simulate a file which opens but cannot be written, a file which opens which cannot be read, or a file which opens but cannot be locked.  I also do not know how to properly test asynchronous I/O within PHPUnit, so these file locking tests were performed manually as above.  If you have a solution, please let me know.

### CODE REVIEW

**Comment by mikegreiling** [comment]
It looks like PHP5.3 does not like ftruncate when applied to streams...

It appears the `vfxStream` used in your unit tests only added support for post PHP 5.4:
http://stubbles.org/archives/101-vfsStream-1.1.0-released.html

Not sure what to do about this either.  I believe the test would pass in an actual file system.  Please advise.

**Comment by mikegreiling** [comment]
Alright, I've finally gotten this to pass and to 100% code coverage.  Let me know how it looks.

**Comment by jeremykendall** [comment]
Nice work!

Do you think we could get around the `ftruncate` issue and simplify the write method by simply adding `LOCK_EX` to `file_put_contents`? I haven't used that option before, but the documentation says that it calls `fopen` and then `flock`.

**Comment by mikegreiling** [comment]
I looked into this and it appears that vfsStream does not support the `LOCK_EX` flag on `file_put_contents()` either.

https://github.com/mikey179/vfsStream/wiki/Known-Issues

Apart from that though, I suppose the underlying implementation should be the same.

**Comment by mikegreiling** [comment]
Also, it appears that prior to PHP 5.2.5 the internal implementation was such that a file could accidentally be truncated before obtaining the file lock:
https://bugs.php.net/bug.php?id=43182

Given this it may be preferable to be verbose about it.  Though I suppose this library is incompatible with 5.2 anyway.

**Comment by jeremykendall** [comment]
I grabbed a few spare minutes to look at this tonight. Still reviewing, but here are my notes/thoughts so far.

> I looked into this and it appears that vfsStream does not support the LOCK_EX flag on file_put_contents() either.

That's a bummer, but maybe there's a way around it with some additional test cases and overriding `file_put_contents` like you did with `ftruncate` in the `PublicSuffixListManagerTest`. If we can accomplish that, I _think_ I'd prefer to go with `file_put_contents`.

> Though I suppose this library is incompatible with 5.2 anyway.

Correct. Not worried about < 5.3.

**Comment by mikegreiling** [comment]
I just tried implementing `PublicSuffixListManager::write()` as follows:

```php
protected function write($filename, $data)
{
    $result = @file_put_contents($this->cacheDir . '/' . $filename, $data, LOCK_EX);

    if ($result === false) {
        throw new \Exception("Cannot write '" . $this->cacheDir . '/' . "$filename'");
    }

    return $result;
}
```

As expected, vfsStream doesn't seem to like it, this time regardless of PHP version.

```bash
$ vendor/bin/phpunit 
PHPUnit 4.8.22 by Sebastian Bergmann and contributors.

...............................................................  63 / 309 ( 20%)
............................................................... 126 / 309 ( 40%)
............................................................... 189 / 309 ( 61%)
............................................................... 252 / 309 ( 81%)
........................EE.E.............................

Time: 18.77 seconds, Memory: 30.25Mb

There were 3 errors:

1) Pdp\PublicSuffixListManagerTest::testRefreshPublicSuffixList
Exception: Cannot write 'vfs://pdp/cache/public-suffix-list.txt'

/Users/mike/Projects/php-domain-parser/src/Pdp/PublicSuffixListManager.php:247
/Users/mike/Projects/php-domain-parser/src/Pdp/PublicSuffixListManager.php:82
/Users/mike/Projects/php-domain-parser/src/Pdp/PublicSuffixListManager.php:65
/Users/mike/Projects/php-domain-parser/tests/src/Pdp/PublicSuffixListManagerTest.php:100

2) Pdp\PublicSuffixListManagerTest::testFetchListFromSource
Exception: Cannot write 'vfs://pdp/cache/public-suffix-list.txt'

/Users/mike/Projects/php-domain-parser/src/Pdp/PublicSuffixListManager.php:247
/Users/mike/Projects/php-domain-parser/src/Pdp/PublicSuffixListManager.php:82
/Users/mike/Projects/php-domain-parser/tests/src/Pdp/PublicSuffixListManagerTest.php:121

3) Pdp\PublicSuffixListManagerTest::testWritePhpCache
Exception: Cannot write 'vfs://pdp/cache/public-suffix-list.php'

/Users/mike/Projects/php-domain-parser/src/Pdp/PublicSuffixListManager.php:247
/Users/mike/Projects/php-domain-parser/src/Pdp/PublicSuffixListManager.php:185
/Users/mike/Projects/php-domain-parser/tests/src/Pdp/PublicSuffixListManagerTest.php:142

FAILURES!
Tests: 309, Assertions: 630, Errors: 3.

Generating code coverage report in HTML format ... done
```

I could override `file_put_contents` to remove the `LOCK_EX` flag with something like the following, but it feels a bit like cheating.  Let me know what you think.
```php
namespace Pdp;

function file_put_contents($path, $data, $flags, $context) {
    $flags &= ~LOCK_EX;
    return @\file_put_contents($path, $data, $flags, $context); 
}
```

You can check out the alternate branch I've created here:
https://github.com/mikegreiling/php-domain-parser/compare/develop...file_locking_alt

**Comment by jeremykendall** [comment]
> I could override file_put_contents to remove the LOCK_EX flag with something like the following, but it feels a bit like cheating.

Yeah, considering that vfsStream can't handle the `LOCK_EX` flag, I would tend to agree. I hate to dump `file_put_contents` for the more verbose alternative, but I feel like test coverage is more important.

**Comment by jeremykendall** [comment]
Kinda surprised there's not a userland library for atomic reads and writes. That's a bummer.

**Comment by nyamsprod** [comment]
@mikegreiling   a new version of PDP has been released with support for PSR-16 as such this PR will be closed has it fixes an issue on version 3.0 using an incorrect branch.

**Pull request closed without merging**
