### PR TITLE
Support PHP 8

### LINKED ISSUE #287: PHP 8
## Issue summary

Please support PHP 8

Thank you.

### PR DESCRIPTION
**Pull request by szepeviktor**
## Introduction

Support PHP 8 as tests already pass.

Fixes #287

### CODE REVIEW

**Comment by szepeviktor** [comment]
Giving up :(

**Comment by nyamsprod** [comment]
@szepeviktor thanks for the PR. I'll look into it more carefully this week but I'll have to admit I'm currently focused in finished the next major version of the library you can already see the code in the [feature/v6 branch](https://github.com/jeremykendall/php-domain-parser/tree/feature/v6) to be able to release it around the time PHP8 hits. Which means that the new version will support PHP7.4 *and* PHP8. 

I might then release the two aroud the same time but I'll mainly focus on v6 and v5 will only receive security fixes if any for another 6 months.

**Comment by szepeviktor** [comment]
You're welcome.
All right. Removing `--ignore-platform-reqs` should be enough.

**Comment by nyamsprod** [comment]
@szepeviktor I'll be switching the package over using githubs actions instead of travis. So I'll close this PR after and will make sure to include PHP8 in the actions like I've already did for the feature/v6 branch.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
This is a highly usable integration test suite for PHP/GHA
https://github.com/ergebnis/php-library-template/blob/main/.github/workflows/integrate.yaml

**Pull request closed without merging**
