### PR TITLE
Improve bugfix for #321 and fixes #334

### LINKED ISSUE #334: Private domains containing multi-level suffixes are unresolvable
## Issue summary

The changes introduced with https://github.com/jeremykendall/php-domain-parser/pull/322 broke the resolution of private domains that contain valid higher-level suffixes.

For example, consider the TLD `eu.org` - it is listed as a valid private domain, but it is also a part of other valid private domains:
```
// EU.org https://eu.org/
// Submitted by Pierre Beyssac <hostmaster@eu.org>
eu.org
al.eu.org
asso.eu.org
at.eu.org
au.eu.org
...
```
After the changes in https://github.com/jeremykendall/php-domain-parser/pull/322, domains such as `test-domain.eu.org` are not recognised as private domains:
`PHP Fatal error:  Uncaught Pdp\UnableToResolveDomain: The domain "test-domain.eu.org" does not contain a "private" TLD.`

Only lower-level entries, such as `test-domain.au.eu.org` are recognised properly.

### System informations

| Information | Description |
|--------------|---------|
| Pdp version |  6.1.1 |
| PHP version | * |
| OS Platform | * |

## Standalone code, or other way to reproduce the problem
```php
$domain = $publicSuffixList->getPrivateDomain("test-domain.eu.org");
die('private domain', json_encode([
    'domain' => $domain->domain(),
    'subdomain' => $domain->subDomain(),
    'registrable_domain' => $domain->registrableDomain(),
    'second_level_domain' => $domain->secondLevelDomain(),
]));
```

### Expected result
`private domain {"domain":"test-domain.eu.org","subdomain":null,"registrable_domain":"test-domain.eu.org","second_level_domain":"test-domain"}`
### Actual result
`PHP Fatal error:  Uncaught Pdp\UnableToResolveDomain: The domain "test-domain.eu.org" does not contain a "private" TLD.`

### PR DESCRIPTION
**Pull request by nyamsprod**
- Improve #321 bugfix
- Fixes issue #334 

@laurynasgadl can you validate the fix ?

### CODE REVIEW

**Comment by laurynasgadl** [comment]
This fix works for the provided example of `eu.org` -> `test-domain.eu.org` and `test-domain.lt.eu.org`.

However, there is a case where it would not work (not sure if such scenario is possible), e.g. the current `eu.org` list is:
```
eu.org // 2 labels
al.eu.org // 3 labels
asso.eu.org // 3 labels
...
```
the fix works with such case, but it would not work with something like this:
```
eu.org // 2 labels
abc.al.eu.org // 4 labels
asso.eu.org // 3 labels
```
Both `test-domain.eu.org` and `test-domain.lt.eu.org` fail to be resolved as private domains, because the first entry that follows `eu.org` (`abc.al.eu.org` in this case), contains child TLDs (['al' => ['abc' => []]]) and the `[] !== reset($rules)` check fails.

If such ordering is not possible in the domain list then the fix is valid, otherwise it would need adjustments.

**Comment by laurynasgadl** [comment]
This fix works for the provided example of `eu.org` -> `test-domain.eu.org` and `test-domain.lt.eu.org`.

However, there is a case where it would not work, e.g. the current `eu.org` list is:
```
eu.org // 2 labels
al.eu.org // 3 labels
...
```
the fix works with such case, but it would not work with something like this:
```
eu.org // 2 labels
abc.al.eu.org // 4 labels
```
`test-domain.eu.org` fails to be resolved as private domain, because the first entry that follows `eu.org` (`abc.al.eu.org` in this case), contains child TLDs (['al' => ['abc' => []]]) and the `[] !== reset($rules)` check fails.

**Comment by nyamsprod** [comment]
Sorting when adding new suffix to the list *MUST* follow https://github.com/publicsuffix/list/wiki/Format#right-to-left-sorting

So I believe the fix does cover it unless I read it wrongly

**Comment by laurynasgadl** [comment]
If cases where the following suffix differs by more than a single label are not possible, e.g.:
```
example.tld
one.two.example.tld
// two.example.tld is NOT in the list
```
Then this is does fix it.

**Pull request merged**
